### ISSUE TITLE
Devcontainer.json API, Az Func and Terraform to create

### ISSUE THREAD

**Issue by Justrebl** [microsoft/hands-on-lab-redis#11]
```[tasklist]
### Tasks
- [x] terraform
- [x] azure func + ext
- [x] Http Rest
- [x] ext app service
- [x] ext pour redis
```
