### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Justrebl** [microsoft/hands-on-lab-redis#4]
Todos for the coming Lab preparation : 

```[tasklist]
### Tasks
- [ ] Set the Lab Structure : Redis Introduction (Play with the console and Redis structures) / PaaS integration (Cache aside & Write Behind) / Event Driven Architecture (ACA / Function).
- [ ] Test Redis integration with Dapr + ACA
- [ ] Connect Redis Insight to Azure Cache for Redis (Entrerprise?)
```
